### ISSUE TITLE
"Completed" checker pods should have got deleted but they didn't

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [Comcast/kuberhealthy#799]
**Describe the bug**
I ran a khcheck at a rate of 3 minutes for 2 days and found the namespace to be filled with ~1900 pods in "Completed" state. Ideally, kuberhealthy should have deleted the pods which reached "Completed" state like k8s's `kind: CronJob` does via considering the `successfulJobsHistoryLimit`

**Steps To Reproduce**
- Run a khcheck at a quick interval like 10s
- Wait for a few minutes and then, enter the command `kubectl get pods -n kuberhealthy | grep "Completed"`

**Expected behavior**
All the pods in "Completed" should ve been automatically deleted or no more than `successfulJobsHIstoryLimit` (default: 3) number of  latest "Completed" pods should ve been allowed to persist and rest of them should ve been deleted by kuberhealthy.

**Comment by talonx** [comment]
I evaluated kuberhealthy recently and I'm hesitant to use it for precisely this reason. The kuberhealthy namespace gets cluttered with hundreds of pods after sometime.

**Comment by integrii** [comment]
We know about this one... The check-reper cronjob fixes this by removing the pods that you describe as stacking up, but if the kubernetes cronjob gets stuck for some reason or the check-reper pod can't schedule, then you get this behavior.  

To make this more durable, we are going to move the check reaper into the main Kuberhealthy binary in issue #774 ...  This shouldn't be a big change and should fix this issue.

**Comment by yashvardhan-kukreja** [comment]
Ohh @integrii , I get it why my "Completed" pods were not getting cleaned up.
That's because, whenever I install kuberhealthy with helm, all the manifests get applied EXCEPT check-reaper's one because of the following error:
```
► helm install kuberhealthy kuberhealthy/kuberhealthy                  

Error: CronJob in version "v1beta1" cannot be handled as a CronJob: v1beta1.CronJob.Spec: v1beta1.CronJobSpec.JobTemplate: v1beta1.JobTemplateSpec.Spec: v1.JobSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.v1.EnvVar.Value: ReadString: expects " or n, but found 4, error found in #10 byte of ...|,"value":4},{"name":|..., bigger context ...|"value":""},{"name":"MAX_PODS_THRESHOLD","value":4},{"name":"JOB_DELETE_TIME_DURATION","value":"15m"|...
```

And that's why, check-reaper does not get applied and hence, there's no resource to cleanup the completed pods.

**Comment by yashvardhan-kukreja** [comment]
@integrii I found the solution to resolving this helm error. I'll create an issue and a PR corresponding to this.

**Comment by yashvardhan-kukreja** [comment]
@integrii, Closing this issue,  I have created another issue ( #801 ) addressing the exact error causing the above issue and created a PR that resolves it #802 .

**Comment by talonx** [comment]
I am still seeing this in spite of the check-reaper jobs running. Some are lying around for more than 2 hours. Should I open a different ticket? 

```
NAME                             READY   STATUS      RESTARTS   AGE
check-reaper-1614070800-hv6lx    0/1     Completed   0          6m39s
check-reaper-1614070980-x8jbk    0/1     Completed   0          3m39s
check-reaper-1614071160-lxxrd    0/1     Completed   0          38s
daemonset-1614063641             0/1     Completed   0          125m
daemonset-1614064541             0/1     Completed   0          110m
daemonset-1614065441             0/1     Completed   0          95m
daemonset-1614066341             0/1     Completed   0          80m
daemonset-1614067241             0/1     Completed   0          65m
daemonset-1614068141             0/1     Completed   0          50m
daemonset-1614069041             0/1     Completed   0          35m
daemonset-1614069941             0/1     Completed   0          20m
daemonset-1614070841             0/1     Completed   0          5m58s
deployment-1614063642            0/1     Completed   0          125m
deployment-1614064241            0/1     Completed   0          115m
deployment-1614064841            0/1     Completed   0          105m
deployment-1614065441            0/1     Completed   0          95m
deployment-1614066041            0/1     Completed   0          85m
deployment-1614066641            0/1     Completed   0          75m
deployment-1614067241            0/1     Completed   0          65m
deployment-1614067841            0/1     Completed   0          55m
deployment-1614068441            0/1     Completed   0          45m
deployment-1614069041            0/1     Completed   0          35m
deployment-1614069641            0/1     Completed   0          25m
deployment-1614070241            0/1     Completed   0          15m
deployment-1614070841            0/1     Completed   0          5m58s
dns-status-internal-1614063641   0/1     Completed   0          125m
dns-status-internal-1614063761   0/1     Completed   0          123m
dns-status-internal-1614063881   0/1     Completed   0          121m
dns-status-internal-1614064001   0/1     Completed   0          119m
dns-status-internal-1614064121   0/1     Completed   0          117m
dns-status-internal-1614064241   0/1     Completed   0          115m
dns-status-internal-1614064361   0/1     Completed   0          113m
dns-status-internal-1614064481   0/1     Completed   0          111m
dns-status-internal-1614064601   0/1     Completed   0          109m
dns-status-internal-1614064721   0/1     Completed   0          107m
dns-status-internal-1614064841   0/1     Completed   0          105m
dns-status-internal-1614064961   0/1     Completed   0          103m
dns-status-internal-1614065081   0/1     Completed   0          101m
........snipped
```
